CourseProject/Models/Entity/AboutEntry.cs
namespace CourseProject.Models.Entity
{
    public class AboutEntry
    {
        public int Id { get; set; }
        public string? FirstTitle { get; set; }
        public string? SecondTitle { get; set; }
        public string? Description { get; set; }
        public string? Image { get; set; }
    }
}

CourseProject/Controllers/AboutEntryController.cs
using CourseProject.Models.Entity;
using CourseProject.Repositories.IRepository;
using Microsoft.AspNetCore.Mvc;

namespace CourseProject.Controllers
{
    public class AboutEntryController : Controller
    {
        private readonly IAboutEntryRepository _aboutEntryRepository;

        public AboutEntryController(IAboutEntryRepository aboutEntryRepository)
        {
            _aboutEntryRepository = aboutEntryRepository;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var value = await _aboutEntryRepository.GetAsync(1);
            return View(value);
        }
        [HttpPost]
        public async Task<IActionResult> Index(AboutEntry aboutEntry) 
        {
            if (HttpContext.Request.Form.Files.Count != 0 && !string.IsNullOrEmpty(HttpContext.Request.Form.Files[0].FileName))
            {
                IFormFile file = HttpContext.Request.Form.Files[0];
                string filename = Path.GetFileNameWithoutExtension(file.FileName);
                string extension = Path.GetExtension(file.FileName);
                string imgFilePath = Path.Combine("wwwroot", "aboutEntryImage", filename + extension);

                using (FileStream stream = new FileStream(imgFilePath, FileMode.Create))
                {
                    file.CopyTo(stream);
                }
                aboutEntry.Image = "/aboutEntryImage/" + filename + extension;
            }
            await _aboutEntryRepository.UpdateAsync(aboutEntry);
            return RedirectToAction("Index");
        }
    }
}

CourseProject/Views/AboutEntry/Index.cshtml
@model CourseProject.Models.Entity.AboutEntry

@{
    ViewBag.Title = "EditTag";
    Layout = "~/Views/Shared/_AdminPageLayout.cshtml";
}


<div class="container text-center">
    <h1> About Sayfası Girişi Düzenleme Sayfası</h1>
</div>

<div class="container py-5">
    <form method="post" asp-action="Index" asp-controller="AboutEntry" enctype="multipart/form-data">
        <input type="hidden" asp-for="Id" />

        <div class="mb-3">
            <label class="form-label">Başlık</label>
            <input type="text" class="form-control" asp-for="FirstTitle" />
        </div>

        <div class="mb-3">
            <label class="form-label">Alt Başlık</label>
            <input type="text" class="form-control" asp-for="SecondTitle" />
        </div>

        <div class="mb-3">
            <label class="form-label">Açıklama</label>
            <input type="text" class="form-control" asp-for="Description" />
        </div>

        <div class="mb-3">
            <label class="form-label">Maç Resim</label>
            <input type="file" class="form-control" asp-for="Image" />
        </div>

        <div class="mb-3">
            <button type="submit" class="btn btn-dark">
                Kaydet
            </button>
        </div>

    </form>
</div>