CourseProject/Models/Entity/ContactDetail.cs
using System.ComponentModel.DataAnnotations;

namespace CourseProject.Models.Entity
{
    public class ContactDetail {
        [Key]
        public int Id { get; set; }
        public string? Title { get; set; }
        public string? SecondTitle { get; set; }
        public string? Description { get; set; }
        public string? ButtonName {  get; set; }
        public string? PhoneNumber { get; set;}
        public string? EmailAdress { get; set;}
        public string? Adress { get; set; }
    }
}

CourseProject/Controllers/ContactDetailsController.cs
using CourseProject.Models.Entity;
using CourseProject.Repositories.IRepository;
using Microsoft.AspNetCore.Mvc;

namespace CourseProject.Controllers
{
    public class ContactDetailsController : Controller
    {
        private readonly IContactDetailsRepository _contactDetailsRepository;

        public ContactDetailsController(IContactDetailsRepository contactDetailsRepository)
        {
            _contactDetailsRepository = contactDetailsRepository;
        }
        public async Task<IActionResult> Index()
        {
            var value = await _contactDetailsRepository.GetAsync(1);
            return View(value);
        }
        [HttpPost]
        public async Task<IActionResult> Index(ContactDetail contactDetail)
        {
            await _contactDetailsRepository.UpdateAsync(contactDetail);
            return RedirectToAction("Index");
        }
    }
}

CourseProject/Views/ContactDetails/Index.cshtml
@model CourseProject.Models.Entity.ContactDetail

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminPageLayout.cshtml";
}

<div class="container text-center">
    <h1> İletişim Düzenleme Sayfası</h1>
</div>

<div class="container py-5">
    <form method="post" asp-action="Index" asp-controller="ContactDetails">

        <input type="hidden" asp-for="Id" />

        <div class="mb-3">
            <label class="form-label">Birinci Başlık</label>
            <input type="text" class="form-control" asp-for="Title" />
        </div>
        <div class="mb-3">
            <label class="form-label">İkinci Başlık</label>
            <input type="text" class="form-control" asp-for="SecondTitle" />
        </div>
        <div class="mb-3">
            <label class="form-label">Açıklama</label>
            <input type="text" class="form-control" asp-for="Description" />
        </div>
        <div class="mb-3">
            <label class="form-label">Buton Adı</label>
            <input type="text" class="form-control" asp-for="ButtonName" />
        </div>
        <div class="mb-3">
            <label class="form-label">Telefon Numarası</label>
            <input type="number" class="form-control" asp-for="PhoneNumber" />
        </div>
        <div class="mb-3">
            <label class="form-label">E-mail Adresi</label>
            <input type="email" class="form-control" asp-for="EmailAdress" />
        </div>
        <div class="mb-3">
            <label class="form-label">Açık Adres</label>
            <input type="text" class="form-control" asp-for="Adress" />
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-dark">
                Kaydet
            </button>
        </div>
    </form>
</div>